In [1]:
import numpy as np
import scipy
from scipy.optimize import curve_fit
import plotly
from plotly import graph_objects as go
import math
from spring_math import *

In [108]:
data0 = [(0.0, 694.0), (3.592800931073725e-05, 694.0), (0.01670259502134286, 694.0), (0.03336926200427115, 693.8657967705899), (0.05003592901630327, 693.515898049579), (0.06670259599923156, 692.9611549755996), (0.08336926301126368, 692.2123672053261), (0.1000359300232958, 691.280261314332), (0.1167025970062241, 690.1754703691031), (0.13336926401825622, 688.908514660918), (0.1500359310011845, 687.4897835901534), (0.16670259801321663, 685.9295186875527), (0.18336926502524875, 684.2377977570935), (0.20003593200817704, 682.4245201233213), (0.21670259902020916, 680.4993929643534), (0.23336926600313745, 678.4719187102305), (0.2500359330151696, 676.3513834848671), (0.2667026000272017, 674.1468465685538), (0.28336926701013, 671.8671308567685), (0.3000359340221621, 669.5208142899758), (0.3167026010050904, 667.1162222281109), (0.3333692680171225, 664.6614207425835), (0.3500359350000508, 662.164210797856), (0.36670260201208293, 659.6321232939857), (0.38336926902411506, 657.0724149409401), (0.40003593600704335, 654.4920649350084), (0.41670260301907547, 651.8977724072386), (0.43336927000200376, 649.2959546135137), (0.4500359370140359, 646.6927458356564), (0.466702604026068, 644.0939969627948), (0.4833692710089963, 641.5052757221533), (0.5000359380210284, 638.9318675284236), (0.5167026050039567, 636.3787769209398), (0.5333692720159888, 633.8507295580126), (0.5500359389989171, 631.3521747379676), (0.5667026060109492, 628.8872884166873), (0.5833692730229814, 626.4599766917619), (0.6000359400059097, 624.0738797237141), (0.6167026070179418, 621.7323760651684), (0.6333692740008701, 619.4385873692925), (0.6500359410129022, 617.1953834493326), (0.6667026080249343, 615.0053876616001), (0.6833692750078626, 612.87098258484), (0.7000359420198947, 610.7943159695147), (0.716702609002823, 608.7773069311775), (0.7333692760148551, 606.8216523627676), (0.7500359430268873, 604.9288335413532), (0.7667026100098155, 603.1001229055555), (0.7833692770218477, 601.3365909806187), (0.800035944004776, 599.6391134288415), (0.8167026110168081, 598.0083782038407), (0.8333692779997364, 596.4448927879014), (0.8500359450117685, 594.9489914924429), (0.8667026120238006, 593.520842802431), (0.8833692790067289, 592.1604567463567), (0.900035946018761, 590.8676922742093), (0.9167026130016893, 589.6422646266707), (0.9333692800137214, 588.4837526795635), (0.9500359470257536, 587.3916062483825), (0.9667026140086818, 586.3651533385403), (0.983369281020714, 585.4036073277482), (1.0000359480036423, 584.5060740677364), (1.0167026150156744, 583.6715588932976), (1.0333692820277065, 582.8989735274029), (1.0500359490106348, 582.187142871897), (1.066702616022667, 581.5348116740233), (1.0833692830055952, 580.9406510597598), (1.1000359500176273, 580.4032649256656), (1.1167026170005556, 579.9211961816397), (1.1333692840125877, 579.4929328376796), (1.1500359510246199, 579.1169139283949), (1.1667026180075482, 578.7915352696875), (1.1833692850195803, 578.5151550426414), (1.2000359520025086, 578.2860992002785), (1.2167026190145407, 578.1026666934397), (1.2333692860265728, 577.96313451262), (1.250035953009501, 577.8657625431487), (1.2667026200215332, 577.8087982316408), (1.2833692870044615, 577.7904810621608), (1.3000359540164936, 577.8090468410369), (1.316702620999422, 577.8627317897415), (1.333369288011454, 577.9497764457001), (1.3500359550234862, 578.0684293713327), (1.3667026220064145, 578.216950672038), (1.3833692890184466, 578.3936153242244), (1.4000359560013749, 578.596716314862), (1.416702623013407, 578.8245675943813), (1.4333692900254391, 579.0755068450699), (1.4500359570083674, 579.3478980674333), (1.4667026240203995, 579.6401339872714), (1.4833692910033278, 579.9506382864942), (1.50003595801536, 580.27786766095), (1.516702625027392, 580.6203137087715), (1.5333692920103204, 580.9765046529575), (1.5500359590223525, 581.3450069021034), (1.5667026260052808, 581.7244264533704), (1.5833692930173129, 582.1134101419432), (1.6000359600002412, 582.5106467413672), (1.6167026270122733, 582.9148679192865), (1.6333692940243054, 583.324849053208), (1.6500359610072337, 583.7394099110186), (1.6667026280192658, 584.1574152010571), (1.6833692950021941, 584.577774996613), (1.7000359620142262, 584.9994450397696), (1.7167026290262584, 585.4214269295542), (1.7333692960091867, 585.8427681993778), (1.7500359630212188, 586.2625622887658), (1.766702630004147, 586.6799484143747), (1.7833692970161792, 587.0941113452905), (1.8000359639991075, 587.5042810875732), (1.8167026310111396, 587.9097324829916), (1.8333692980231717, 588.3097847268438), (1.8500359650061, 588.7038008097172), (1.8667026320181321, 589.0911868879789), (1.8833692990010604, 589.471391587724), (1.9000359660130925, 589.8439052468391), (1.9167026330251247, 590.2082590997516), (1.933369300008053, 590.5640244093579), (1.950035967020085, 590.910811550523), (1.9667026340030134, 591.2482690494533), (1.9833693010150455, 591.5760825831353)]
start_offset = 2.001131102995714
fromY = 591.7943990327977
data = [(0.0, 591.8939739429327), (5.3652009228244424e-05, 591.8939739429327), (0.016720318992156535, 592.2914590205689), (0.03338698600418866, 592.8964394626507), (0.05005365301622078, 593.6978801462407), (0.06672031999914907, 594.6848246574667), (0.08338698701118119, 595.8464159675108), (0.10005365399410948, 597.1719159220906), (0.1167203210061416, 598.6507235565274), (0.13338698801817372, 600.2723922505401), (0.15005365500110202, 602.0266457388265), (0.16672032201313414, 603.9033929952814), (0.18338698899606243, 605.8927420103744), (0.20005365600809455, 607.985012482757), (0.21672032299102284, 610.1707474475994), (0.23338699000305496, 612.4407238654661), (0.2500536570150871, 614.7859621967444), (0.2667203239980154, 617.1977349877185), (0.2833869910100475, 619.6675744953666), (0.3000536579929758, 622.1872793788268), (0.3167203250050079, 624.7489204862477), (0.33338699201704003, 627.3448457664092), (0.3500536589999683, 629.9676843350733), (0.36672032601200044, 632.6103497265005), (0.38338699299492873, 635.2660423609626), (0.40005366000696085, 637.9282512593787), (0.416720327018993, 640.5907550364278), (0.43338699400192127, 643.247622203625), (0.4500536610139534, 645.8932108139148), (0.4667203279968817, 648.5221674793244), (0.4833869950089138, 651.1294257931389), (0.5000536619918421, 653.7102041879165), (0.5167203290038742, 656.2600032604505), (0.5333869960159063, 658.7746025945203), (0.5500536629988346, 661.2500571119463), (0.5667203300108667, 663.6826929820876), (0.583386996993795, 666.0691031194984), (0.6000536640058272, 668.40614229898), (0.6167203310178593, 670.6909219167579), (0.6333869980007876, 672.9208044259528), (0.6500536650128197, 675.0933974739243), (0.666720331995748, 677.2065477684414), (0.6833869990077801, 679.258334698978), (0.7000536659907084, 681.2470637387456), (0.7167203330027405, 683.1712596523686), (0.7333870000147726, 685.0296595333765), (0.7500536669977009, 686.8212056949345), (0.766720334009733, 688.5450384364693), (0.7833870009926613, 690.2004887080615), (0.8000536680046935, 691.7870706936845), (0.8167203350167256, 693.3044743335646), (0.8333870019996539, 694.7525578051237), (0.850053669011686, 696.1313399811537), (0.8667203359946143, 697.440992883045), (0.8833870030066464, 698.6818341460776), (0.9000536700186785, 699.8543195129538), (0.9167203370016068, 700.9590353709422), (0.9333870040136389, 701.9966913471789), (0.9500536709965672, 702.9681129758709), (0.9667203380085994, 703.8742344503402), (0.9833870049915276, 704.7160914720553), (1.0000536720035598, 705.4948142080161), (1.016720339015592, 706.2116203670837), (1.0333870059985202, 706.8678084050879), (1.0500536730105523, 707.464750867803), (1.0667203399934806, 708.0038878801472), (1.0833870070055127, 708.4867207892482), (1.1000536740175448, 708.9148059683183), (1.1167203410004731, 709.2897487876003), (1.1333870080125052, 709.6131977579814), (1.1500536749954335, 709.8868388522295), (1.1667203420074657, 710.112390008175), (1.1833870090194978, 710.291595817561), (1.200053676002426, 710.4262224036949), (1.2167203430144582, 710.5180524904669), (1.2333870099973865, 710.5688806647612), (1.2500536770094186, 710.5805088337547), (1.266720343992347, 710.5547418781005), (1.283387011004379, 710.4933835015071), (1.3000536780164111, 710.3982322767689), (1.3167203449993394, 710.271077887858), (1.3333870120113716, 710.1136975672763), (1.3500536789942998, 709.9278527274645), (1.366720346006332, 709.7152857846946), (1.383387013018364, 709.4777171735149), (1.4000536800012924, 709.2168425494816), (1.4167203470133245, 708.9343301776064), (1.4333870139962528, 708.6318185036449), (1.450053681008285, 708.3109139050895), (1.4667203479912132, 707.9731886184705), (1.4833870150032453, 707.6201788393396), (1.5000536820152774, 707.253382991092), (1.5167203489982057, 706.8742601585933), (1.5333870160102379, 706.4842286823916), (1.5500536829931661, 706.0846649091441), (1.5667203500051983, 705.676902093735), (1.5833870170172304, 705.2622294484457), (1.6000536840001587, 704.8418913344199), (1.6167203510121908, 704.417086590574), (1.633387017995119, 703.9889679950296), (1.6500536850071512, 703.5586418540726), (1.6667203520191833, 703.1271677135973), (1.6833870190021116, 702.6955581879577), (1.7000536860141438, 702.2647789011218), (1.716720352997072, 701.8357485350167), (1.7333870200091042, 701.4093389799484), (1.7500536869920325, 700.9863755819978), (1.7667203540040646, 700.5676374823114), (1.7833870210160967, 700.153858043243), (1.800053687999025, 699.7457253563416), (1.816720355011057, 699.3438828272352), (1.8333870219939854, 698.9489298325183), (1.8500536890060175, 698.5614224438209), (1.8667203560180496, 698.1818742143128), (1.883387023000978, 697.8107570229776), (1.90005369001301, 697.4485019720831), (1.9167203569959383, 697.0955003333696), (1.9333870240079705, 696.7521045385756), (1.9500536909908988, 696.4186292100316), (1.9667203580029309, 696.0953522271572), (1.983387025014963, 695.7825158248169), (2.0000536919978913, 695.4803277196039), (2.0167203590099234, 695.1889622602447), (2.0333870259928517, 694.908561598441), (2.050053693004884, 694.6392368765931), (2.066720360016916, 694.3810694289749), (2.0833870269998442, 694.1341119930635), (2.1000536940118764, 693.8983899278567), (2.1167203609948047, 693.6739024361449), (2.1333870280068368, 693.4606237878345), (2.150053695018869, 693.2585045415558), (2.166720362001797, 693.0674727619202), (2.1833870290138293, 692.8874352299247), (2.2000536959967576, 692.7182786441329), (2.2167203630087897, 692.5598708103931), (2.233387029991718, 692.4120618179867), (2.25005369700375, 692.2746852002228), (2.2667203640157823, 692.1475590776305), (2.2833870309987105, 692.0304872820162), (2.3000536980107427, 691.9232604597844), (2.316720364993671, 691.8256571530371), (2.333387032005703, 691.7374448570861), (2.350053699017735, 691.6583810531299), (2.3667203660006635, 691.5882142149611), (2.3833870330126956, 691.5266847886766), (2.400053699995624, 691.4735261444766), (2.416720367007656, 691.4284654997399), (2.433387034019688, 691.3912248126637), (2.4500537010026164, 691.361521645859), (2.4667203680146486, 691.3390699993828), (2.483387034997577, 691.3235811127843), (2.500053702009609, 691.31476423583), (2.5167203689925373, 691.312327367656), (2.5333870360045694, 691.3159779641805), (2.5500537030166015, 691.3254236136854), (2.56672036999953, 691.340372680553), (2.583387037011562, 691.3605349172136), (2.60005370399449, 691.3856220444289), (2.6167203710065223, 691.4153483001005), (2.6333870380185544, 691.4494309568515), (2.6500537050014827, 691.4875908086933), (2.666720372013515, 691.5295526271356), (2.683387038996443, 691.5750455871549), (2.7000537060084753, 691.6238036634829), (2.7167203729914036, 691.6755659977186), (2.7333870400034357, 691.7300772368118), (2.750053707015468, 691.7870878435023), (2.766720373998396, 691.8463543793347), (2.783387041010428, 691.9076397609011), (2.8000537079933565, 691.9707134899905), (2.8167203750053886, 692.0353518583549), (2.8333870420174208, 692.1013381278199), (2.850053709000349, 692.1684626864923), (2.866720376012381, 692.2365231818336), (2.8833870429953095, 692.305324631384), (2.9000537100073416, 692.3746795119337), (2.9167203770193737, 692.4444078279522), (2.933387044002302, 692.5143371600892), (2.950053711014334, 692.5843026945721), (2.9667203779972624, 692.6541472343266), (2.9833870450092945, 692.7237211926484), (3.000053711992223, 692.7928825702561), (3.016720379004255, 692.8614969165508), (3.033387046016287, 692.929437275909), (3.0500537129992153, 692.9965841198234), (3.0667203800112475, 693.0628252657066), (3.0833870469941758, 693.1280557831586), (3.100053714006208, 693.1921778884944), (3.11672038101824, 693.2551008283114), (3.1333870480011683, 693.3167407528701), (3.1500537150132004, 693.3770205800437), (3.1667203819961287, 693.4358698505789), (3.183387049008161, 693.4932245753981), (3.200053715991089, 693.5490270756502), (3.2167203830031212, 693.6032258162072), (3.2333870500151534, 693.6557752332823), (3.2500537169980817, 693.7066355568248), (3.2667203840101138, 693.755772628335), (3.283387050993042, 693.8031577147119), (3.300053718005074, 693.8487673187394), (3.3167203850171063, 693.8925829867837), (3.3333870520000346, 693.934591114262), (3.3500537190120667, 693.9747827494194), (3.366720385994995, 694.0131533959283), (3.383387053007027, 694.0497028148027), (3.4000537200190593, 694.0844348261037), (3.4167203870019875, 694.1173571108817), (3.4333870540140197, 694.148481013788), (3.450053720996948, 694.177821346762), (3.46672038800898, 694.20539619418), (3.4833870549919084, 694.2312267198307), (3.5000537220039405, 694.255336976061), (3.5167203890159726, 694.2777537154151), (3.533387055998901, 694.2985062050684), (3.550053723010933, 694.31762604434), (3.5667203899938613, 694.3351469855425), (3.5833870570058934, 694.3511047584145), (3.6000537240179256, 694.3655368983575), (3.616720391000854, 694.3784825786802), (3.633387058012886, 694.389982447038), (3.6500537249958143, 694.4000784662337), (3.6667203920078464, 694.4088137595296), (3.6833870589907747, 694.416232460606), (3.700053726002807, 694.42237956828), (3.716720393014839, 694.4273008060865), (3.733387059997767, 694.431042486807), (3.7500537270097993, 694.4336513820147), (3.7667203939927276, 694.4351745966931), (3.7833870610047597, 694.4356594489686), (3.800053728016792, 694.4351533549866), (3.81672039499972, 694.4337037189456), (3.8333870620117523, 694.4313578282946), (3.8500537289946806, 694.4281627540832), (3.8667203960067127, 694.4241652564475), (3.883387063018745, 694.4194116952006), (3.900053730001673, 694.4139479454885), (3.9167203970137052, 694.407819318463), (3.9333870639966335, 694.4010704869113), (3.9500537310086656, 694.3937454157796), (3.966720397991594, 694.3858872975128), (3.983387065003626, 694.377538492133), (4.000053732015658, 694.3687404719644), (4.0167203989985865, 694.3595337709147), (4.033387066010619, 694.3499579382091), (4.050053732993547, 694.3400514964752), (4.066720400005579, 694.3298519040661), (4.083387067017611, 694.319395521509), (4.100053734000539, 694.3087175819603), (4.1167204010125715, 694.2978521655472), (4.1333870679955, 694.2868321774693), (4.150053735007532, 694.2756893297347), (4.166720402019564, 694.2644541264015), (4.183387069002492, 694.2531558521923), (4.2000537360145245, 694.2418225643521), (4.216720402997453, 694.2304810876127), (4.233387070009485, 694.2191570121338), (4.250053736992413, 694.2078746942822), (4.266720404004445, 694.1966572601186), (4.283387071016477, 694.185526611455), (4.300053737999406, 694.1745034343502), (4.316720405011438, 694.1636072099113), (4.333387071994366, 694.1528562272689), (4.350053739006398, 694.1422675985947), (4.36672040601843, 694.1318572760347), (4.383387073001359, 694.1216400704294), (4.400053740013391, 694.1116296716963), (4.416720406996319, 694.1018386707525), (4.433387074008351, 694.0922785828549), (4.4500537409912795, 694.0829598722428), (4.466720408003312, 694.0738919779641), (4.483387075015344, 694.0650833407749), (4.500053741998272, 694.0565414310012), (4.516720409010304, 694.0482727772566), (4.533387075993232, 694.0402829959118), (4.5500537430052646, 694.032576821215), (4.566720410017297, 694.0251581359668), (4.583387077000225, 694.0180300026545), (4.600053744012257, 694.0111946949562), (4.616720410995185, 694.0046537295258), (4.6333870780072175, 693.9984078979771), (4.65005374501925, 693.9924572989854), (4.666720412002178, 693.9868013704296), (4.68338707901421, 693.9814389215024), (4.700053745997138, 693.976368164718), (4.71672041300917, 693.9715867477513), (4.733387079992099, 693.9670917850451), (4.750053747004131, 693.962879889127), (4.766720414016163, 693.9589472015788), (4.783387080999091, 693.9552894236064), (4.800053748011123, 693.9519018461613), (4.816720414994052, 693.9487793795661), (4.833387082006084, 693.9459165826038), (4.850053749018116, 693.9433076910286), (4.866720416001044, 693.9409466454639), (4.883387083013076, 693.9388271186535), (4.900053749996005, 693.936942542035), (4.916720417008037, 693.9352861316082), (4.933387083990965, 693.9338509130758), (4.950053751002997, 693.9326297462311), (4.966720418015029, 693.9316153485761), (4.983387084997958, 693.9308003181536), (5.00005375200999, 693.9301771555777), (5.016720418992918, 693.9297382852516), (5.03338708600495, 693.9294760757654), (5.050053753016982, 693.9293828594635), (5.0667204199999105, 693.9294509511805), (5.083387087011943, 693.9296726661388), (5.100053753994871, 693.9300403370122), (5.116720421006903, 693.9305463301514), (5.133387088018935, 693.9311830609782), (5.1500537550018635, 693.9319430085516), (5.166720422013896, 693.9328187293113), (5.183387088996824, 693.9338028700088), (5.200053756008856, 693.9348881798325), (5.216720422991784, 693.9360675217396), (5.233387090003816, 693.9373338830059), (5.2500537570158485, 693.938680385006), (5.266720423998777, 693.9401002922398), (5.283387091010809, 693.9415870206177), (5.300053757993737, 693.9431341450245), (5.316720425005769, 693.9447354061742), (5.3333870920178015, 693.9463847167785), (5.35005375900073, 693.948076167043), (5.366720426012762, 693.9498040295138), (5.38338709299569, 693.9515627632907), (5.400053760007722, 693.9533470176311), (5.416720426990651, 693.9551516349613), (5.433387094002683, 693.9569716533184), (5.450053761014715, 693.9588023082433), (5.466720427997643, 693.9606390341468), (5.483387095009675, 693.962477465169), (5.5000537619926035, 693.9643134355553), (5.516720429004636, 693.9661429795702), (5.533387096016668, 693.96796233097), (5.550053762999596, 693.9697679220567), (5.566720430011628, 693.9715563823357), (5.5833870969945565, 693.973324536797), (5.600053764006589, 693.9750694038423), (5.616720431018621, 693.9767881928797), (5.633387098001549, 693.9784783016047), (5.650053765013581, 693.980137312992), (5.666720431996509, 693.9817629920138), (5.6833870990085416, 693.9833532821078), (5.70005376599147, 693.9849063014136), (5.716720433003502, 693.9864203387964), (5.733387100015534, 693.9878938496768), (5.750053766998462, 693.9893254516854), (5.7667204340104945, 693.9907139201598), (5.783387100993423, 693.9920581835011), (5.800053768005455, 693.993357318407), (5.816720435017487, 693.9946105449992), (5.833387102000415, 693.9958172218571), (5.8500537690124474, 693.9969768409786), (5.866720435995376, 693.998089022677), (5.883387103007408, 693.9991535104333), (5.90005377001944, 694.0001701657134), (5.916720437002368, 694.001138962766), (5.9333871040144, 694.0020599834135), (5.950053770997329, 694.0029334118445), (5.966720438009361, 694.0037595294258), (5.983387104992289, 694.0045387095365), (6.000053772004321, 694.0052714124425), (6.016720439016353, 694.0059581802151), (6.033387105999282, 694.0065996317055), (6.050053773011314, 694.0071964575841), (6.066720439994242, 694.0077494154507), (6.083387107006274, 694.0082593250253), (6.100053774018306, 694.008727063425), (6.116720441001235, 694.0091535605337), (6.133387108013267, 694.0095397944712), (6.150053774996195, 694.0098867871665), (6.166720442008227, 694.0101956000402), (6.183387108991155, 694.0104673298016), (6.2000537760031875, 694.0107031043624), (6.21672044301522, 694.0109040788731), (6.233387109998148, 694.011071431883), (6.25005377701018, 694.0112063616284), (6.266720443993108, 694.0113100824495), (6.2833871110051405, 694.0113838213399), (6.300053778017173, 694.0114288146278), (6.316720445000101, 694.0114463047929), (6.333387112012133, 694.0114375374168), (6.350053778995061, 694.0114037582705), (6.366720446007093, 694.0113462105361), (6.3833871130191255, 694.0112661321647), (6.400053780002054, 694.0111647533693), (6.416720447014086, 694.0110432942521), (6.433387113997014, 694.0109029625644), (6.450053781009046, 694.0), (6.466720447991975, 694.0), (6.483387115004007, 694.0), (6.500053782016039, 694.0), (6.516720448998967, 694.0), (6.533387116010999, 694.0), (6.550053782993928, 694.0), (6.56672045000596, 694.0), (6.583387117017992, 694.0), (6.60005378400092, 694.0), (6.616720451012952, 694.0), (6.6333871179958805, 694.0), (6.650053785007913, 694.0), (6.666720451990841, 694.0), (6.683387119002873, 694.0), (6.700053786014905, 694.0), (6.7167204529978335, 694.0), (6.733387120009866, 694.0), (6.750053786992794, 694.0), (6.766720454004826, 694.0), (6.783387121016858, 694.0), (6.800053787999786, 694.0), (6.816720455011819, 694.0), (6.833387121994747, 694.0), (6.850053789006779, 694.0), (6.866720456018811, 694.0), (6.883387123001739, 694.0), (6.9000537900137715, 694.0), (6.9167204569967, 694.0), (6.933387124008732, 694.0), (6.95005379099166, 694.0), (6.966720458003692, 694.0), (6.9833871250157245, 694.0), (7.000053791998653, 694.0), (7.016720459010685, 694.0), (7.033387125993613, 694.0), (7.050053793005645, 694.0), (7.066720460017677, 694.0), (7.083387127000606, 694.0), (7.100053794012638, 694.0), (7.116720460995566, 694.0), (7.133387128007598, 694.0), (7.15005379501963, 694.0), (7.166720462002559, 694.0), (7.183387129014591, 694.0), (7.200053795997519, 694.0), (7.216720463009551, 694.0), (7.2333871299924795, 694.0), (7.250053797004512, 694.0), (7.266720464016544, 694.0), (7.283387130999472, 694.0), (7.300053798011504, 694.0), (7.316720464994432, 694.0), (7.3333871320064645, 694.0), (7.350053799018497, 694.0), (7.366720466001425, 694.0), (7.383387133013457, 694.0), (7.400053799996385, 694.0), (7.4167204670084175, 694.0), (7.433387133991346, 694.0), (7.450053801003378, 694.0), (7.46672046801541, 694.0), (7.483387134998338, 694.0), (7.50005380201037, 694.0), (7.516720468993299, 694.0), (7.533387136005331, 694.0), (7.550053803017363, 694.0), (7.566720470000291, 694.0), (7.583387137012323, 694.0), (7.600053803995252, 694.0), (7.616720471007284, 694.0), (7.633387138019316, 694.0), (7.650053805002244, 694.0), (7.666720472014276, 694.0), (7.683387138997205, 694.0), (7.700053806009237, 694.0), (7.716720472992165, 694.0), (7.733387140004197, 694.0), (7.750053807016229, 694.0), (7.7667204739991575, 694.0), (7.78338714101119, 694.0), (7.800053807994118, 694.0), (7.81672047500615, 694.0), (7.833387142018182, 694.0), (7.8500538090011105, 694.0), (7.866720476013143, 694.0), (7.883387142996071, 694.0), (7.900053810008103, 694.0), (7.916720476991031, 694.0), (7.933387144003063, 694.0), (7.950053811015096, 694.0), (7.966720477998024, 694.0), (7.983387145010056, 694.0), (8.000053811992984, 694.0), (8.016720479005016, 694.0), (8.033387146017049, 694.0), (8.050053812999977, 694.0), (8.066720480012009, 694.0), (8.083387146994937, 694.0), (8.10005381400697, 694.0), (8.116720481019001, 694.0), (8.13338714800193, 694.0), (8.150053815013962, 694.0), (8.16672048199689, 694.0), (8.183387149008922, 694.0), (8.20005381599185, 694.0), (8.216720483003883, 694.0), (8.233387150015915, 694.0), (8.250053816998843, 694.0), (8.266720484010875, 694.0), (8.283387150993804, 694.0), (8.300053818005836, 694.0), (8.316720485017868, 694.0), (8.333387152000796, 694.0), (8.350053819012828, 694.0), (8.366720485995756, 694.0), (8.383387153007789, 694.0), (8.400053819990717, 694.0), (8.416720487002749, 694.0), (8.433387154014781, 694.0), (8.45005382099771, 694.0), (8.466720488009742, 694.0), (8.48338715499267, 694.0), (8.500053822004702, 694.0), (8.516720489016734, 694.0), (8.533387155999662, 694.0), (8.550053823011694, 694.0), (8.566720489994623, 694.0), (8.583387157006655, 694.0), (8.600053824018687, 694.0), (8.616720491001615, 694.0), (8.633387158013647, 694.0), (8.650053824996576, 694.0), (8.666720492008608, 694.0), (8.683387158991536, 694.0), (8.700053826003568, 694.0), (8.7167204930156, 694.0), (8.733387159998529, 694.0), (8.75005382701056, 694.0), (8.766720493993489, 694.0)]


In [109]:
data0 = np.array(data0)
data = np.array(data)

In [110]:
datac = concat(data0, data, start_offset)

In [111]:
t, y = t_y_from_data(datac, 0, 1)

In [112]:
go.FigureWidget([go.Scatter(x=t, y=y)])

FigureWidget({
    'data': [{'type': 'scatter',
              'uid': '7c8212d5-86bc-404d-994d-ced6c5ec4d32',
 …

In [113]:
# start 594, end 694
t, y = t_y_from_data(data0, 694, 594)

In [114]:
mean, cov = curve_fit(spring, t, y, (0, 1, 0.1, 0), bounds=([-np.inf, 0, 0, -np.inf], [np.inf, np.inf, np.inf, np.inf]))

In [115]:
mean

array([0.0167026 , 2.86283667, 0.50119428, 0.01363805])

In [117]:
2 * np.pi / mean[1]

2.1947411033030906

In [116]:
np.sqrt(np.diag(cov))

array([2.53527657e-10, 1.03754603e-11, 1.69715945e-12, 2.08914272e-09])

In [118]:
go.FigureWidget([go.Scatter(x=t, y=y), go.Scatter(x=t, y=spring(t, 0, 2 * np.pi / 2.2, 0.5, 0))])

FigureWidget({
    'data': [{'type': 'scatter',
              'uid': 'c8083a75-031d-4d43-9a0e-f27c030c0c53',
 …

In [120]:
y_smse(y, spring(t, 0, 2 * np.pi / 2.2, 0.5, 0))

0.01194945487059825

In [121]:
def unknown_start_curve(t, start_y, velocity):
    end_y = 694
    return start_y + (end_y - start_y) * spring(t, 0, 2 * np.pi / 2.2, 0.5, velocity / (end_y - start_y))

In [122]:
t, y = t_y_from_data(data[1:], 0, 1)

In [123]:
mean, cov = curve_fit(unknown_start_curve, t, y, (595, 100))

In [124]:
mean

array([591.90712117,  17.93462652])

In [125]:
np.sqrt(np.diag(cov))

array([0.01041212, 0.04254873])

In [126]:
go.FigureWidget([go.Scatter(x=t, y=y), go.Scatter(x=t, y=unknown_start_curve(t, 591.90712117, 17.93462652))])

FigureWidget({
    'data': [{'type': 'scatter',
              'uid': 'd52a0f8d-0401-460f-a7c0-6162b64f88d9',
 …

In [127]:
y_smse(y, unknown_start_curve(t, 591.90712117, 17.93462652))

0.034481280827991234

In [128]:
def find_t_at_y(x, t):
    start = 695
    end = 594
    return start + (end - start) * spring(t, 0, 2 * np.pi / 2.2, 0.5, 0)

In [129]:
curve_fit(find_t_at_y, [0], 591.90712117, start_offset)

/Users/panyusheng/miniconda3/envs/pytorch/lib/python3.7/site-packages/scipy/optimize/minpack.py:795: OptimizeWarning:

Covariance of the parameters could not be estimated



(array([1.99042454]), array([[inf]]))

In [130]:
find_t_at_y(None, 1.99042454)

591.9071211261046

In [131]:
1.99042454 - start_offset

-0.010706562995714153

#### This time is very near start_offset

In [132]:
def find_t_at_dy(x, t):
    start = 695
    end = 594
    return (end - start) * dspring(t, 0, 2 * np.pi / 2.2, 0.5, 0)

In [133]:
curve_fit(find_t_at_dy, [0], 17.93462652, start_offset)

(array([2.01825993]), array([[inf]]))

In [134]:
find_t_at_dy(None, 2.01825993)

17.93462639905742

In [135]:
2.01825993 - start_offset

0.017128827004285974

#### This time is very near start_offset too